version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Assumindo que seu Dockerfile do frontend está nomeado assim
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certificados:/etc/ssl/certs
      - ./certificados:/etc/ssl/private

  backend:
    build:
      context: ./backend  # Caminho onde está o Dockerfile do backend
      dockerfile: Dockerfile.backend  # Assumindo que seu Dockerfile do backend está nomeado assim
    ports:
      - "8090:8090"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SERVICE_REGION=${AZURE_SERVICE_REGION}
    volumes:
      - ./ssl:/app/ssl
